# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.GWindow = QtWidgets.QGraphicsView(self.centralwidget)
        self.GWindow.setGeometry(QtCore.QRect(10, 10, 551, 541))
        self.GWindow.setObjectName("GWindow")
        self.CommandNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.CommandNumber.setGeometry(QtCore.QRect(730, 10, 64, 31))
        self.CommandNumber.setObjectName("CommandNumber")
        self.BtnSave = QtWidgets.QPushButton(self.centralwidget)
        self.BtnSave.setGeometry(QtCore.QRect(620, 150, 121, 41))
        self.BtnSave.setObjectName("BtnSave")
        self.CommandProgressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.CommandProgressBar.setGeometry(QtCore.QRect(570, 50, 221, 23))
        self.CommandProgressBar.setProperty("value", 24)
        self.CommandProgressBar.setObjectName("CommandProgressBar")
        self.BtnStart = QtWidgets.QPushButton(self.centralwidget)
        self.BtnStart.setGeometry(QtCore.QRect(620, 210, 121, 41))
        self.BtnStart.setObjectName("BtnStart")
        self.BtnStop = QtWidgets.QPushButton(self.centralwidget)
        self.BtnStop.setGeometry(QtCore.QRect(620, 270, 121, 41))
        self.BtnStop.setObjectName("BtnStop")
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(570, 350, 211, 22))
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setSingleStep(10)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(630, 320, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(570, 10, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TELLO управление полётом"))
        self.BtnSave.setText(_translate("MainWindow", "Сохранить маршрут"))
        self.BtnStart.setText(_translate("MainWindow", "Старт"))
        self.BtnStop.setText(_translate("MainWindow", "Посадить"))
        self.label.setText(_translate("MainWindow", "Скорость"))
        self.label_2.setText(_translate("MainWindow", "Счёт команд"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.action.setText(_translate("MainWindow", "О программе"))
        self.action_2.setText(_translate("MainWindow", "Выход"))
